---
- name: Restart Celery
  systemd:
    name: celery
    daemon_reload: true
    state: restarted
  become: true

- name: Restart Celerybeat
  listen:
    - Restart Celery
  systemd:
    name: celerybeat
    daemon_reload: true
    state: restarted
  become: true
