---
- name: Install Python 3 prereqs
  apt:
    update_cache: true
    cache_valid_time: 3600  # 1 hour
    name:
      - python3-venv
      - python3-setuptools
      - python3-dev
      - build-essential
    force_apt_get: true
  become: true
  become_user: root

- name: Install nlisim worker
  pip:
    name:
      - "celery[sqs]<5"
      - "git+https://github.com/NutritionalLungImmunity/girder-nlisim.git"
    virtualenv: "{{ worker_virtualenv }}"
    virtualenv_command: "/usr/bin/python3 -m venv"
    state: latest
  notify:
    - Restart Celery

- name: Install Celery services
  template:
    src: "services/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - "celery.service"
    - "celerybeat.service"
  become: true
  notify:
    - Restart Celery

- name: Enable Celery services
  systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
  loop:
    - celery
    - celerybeat
  become: true
