---
- name: Deploy Girder
  hosts: all
  vars:
    ansible_python_interpreter: auto
  roles:
    - role: girder.mongodb
    - role: girder.girder
    - role: girder.nginx
      vars:
        nginx_hostname: "data.nutritionallungimmunity.org"
        nginx_registration_email: "michael.grauer@kitware.com"
  tasks:
    - name: Install Girder plugins
      pip:
        name:
          - girder-google-analytics
          - git+https://github.com/girder/item_tags.git
          - girder-oauth
          - girder-readme
          - girder-sentry
        virtualenv: "{{ girder_virtualenv }}"
        state: latest
      notify:
        - Build Girder web client
        - Restart Girder
